Converted to perl
Signed-off-by: Matt Bagley <firstlife22@gmail.com>

diff --git a/rsync-device b/rsync-device
--- a/rsync-device
+++ b/rsync-device
@@ -1,376 +1,345 @@
-#!/bin/bash
-
-# changing this will result in having to rehash the devices
-checksummer="md5sum"
-
-# checksum each part, then see if it has changed. If so, copy over.
-# keep a record of backup's checksum, so each part is only read on copy
-# (or would it be better to verify? no, backuppc will do that)
-
-original=
-backup=
+#!/usr/bin/perl
 
 
-# where do we store the saved checksums of the backup device?
-# comment out to ignore (no saved checksums)
-# saved_checksums=/root/saved_checksums
+use strict;
+#use Digest::MD5 qw(md5_base64);
+use String::CRC32;
+use BerkeleyDB;
+use Getopt::Long;
+use File::Sync qw(fsync sync);
 
-# how small do we break the device up for checking. Smaller is better for
-# little changes but may take longer. Larger is better for lots of changes
-# and may be faster.
-# Changing this will invalidate any currenty saved checksums
-mb_per_round=20
-notify_every_mb=500
+# options - source dest
+sub show_help {
 
-# unset any timeout
-unset TMOUT 2>/dev/null
-
-usage() {
-  if [ -n "$1" ] ; then
-    echo
-    echo "$1"
-    echo
-  fi
-cat <<EOF
-  Copy a device or file from one location to another, only copying
-  the changed areas. Checksums can be cached in a file to allow
-  for faster backups.
-  
-  Yes, it is like rsync, but larger checksums and device support (/dev/sda2)
+print
+"Copy a device or file from one location to another, only copying the 
+changed areas. Checksums can be cached in a file to allow for faster backups.
+It is like rsync, but works with devices rather than files (like /dev/sda2)
   
   Usage: ( Options must preceed files/devices. )
   
-     `basename $0` [-srnv] <original> <backup>
+     $0 [--sums /database.db] [-start 1234|/checkpoint.file] 
+     [--block NUM] [--savecp /file] [-nv] <original> <backup>
      
-     `basename $0` -c -s /file [-nv] <backup>
+     $0 --checkonly --sums /database.db [-nv] <backup>
   
   Options:
     
-    -s FILE      File to save of the checksums of backup device/file.
-                 If omitted, checksums are not saved.
-                 
-    -r NUM       Number of megabytes to check at a time, Smaller
-                 is better for little changes, and larger is better
-		 for lots of changes. Speed depend on number of
-		 changes.  Note that changing this will erase
-		 any currently saved checksums. Default is 10.
-		 
-    -n NUM       Print out a status line every NUM of megabytes
-                 checked. Defaults to 500.
-		 
-    -c           Just check the backup device/file. A checksum file (-s)
-                 must be provided, and only one backup can be specified.
-		 Check size (-r) is ignored, as the checksum file has the
-		 needed size in it.
-    
-    -v           Show verbose messages (not currently implemented)
-    
-    -h           Show this help message
-    
-EOF
-  exit 1;
-}
-
-# leave blank
-check_only=
-
-CMDLINE="$*"
-while getopts "s:r:n:cvh" opt ; do
-    case $opt in
-      s) saved_checksums="$OPTARG" ;;
-      v) VERBOSE=1 ;;
-      r) mb_per_round="$OPTARG" ;;
-      n) notify_every_mb="$OPTARG" ;;
-      c) check_only="yes" ;;
-      h) usage ;;
-      *) usage " Error processing arg: $*";;
-    esac
-done
-shift `expr $OPTIND - 1`
-
-
-# left args are the files
-if [ $# -eq 2 ]  && [ -z "$check_only" ] ; then
-  original="$1"
-  backup="$2"
+  --sums FILE   File to save of the checksums of backup device/file.
+                If omitted, checksums are not saved.
+                These files can be gigabytes in size.
+  
+  --block NUM   Specify a different block size (default 4096)
+             
+  --start NUM|FILE   Start at this block (use if it crashes)
+                     or specify checkpoint file
+  
+  --savecp FILE Save checkpoints to this file rather than a tmp file
+             	 
+  --checkonly   Just check the backup device/file. A checksum file (--save)
+                must be provided, and only one backup can be specified.
+                Check size is ignored, as the checksum file has the
+                needed size in it.
+  
+  -v|--verbose  Show verbose messages
    
-elif [ $# -eq 1 ] && [ -n "$check_only" ] ; then
-  backup="$1"
+  -h|--help     Show this help message
 
-else
-  usage "  Incorrect number of files/devices: $*"
-
-fi
-
-# echo "Got orig:$original back:$backup r:$mb_per_round s:$saved_checksums n:$notify_every_mb c:$check_only"
-# exit
-
-# needed so piping command will return 1 with _any_ fail
-set -o pipefail
-
-get_sum() {
-  device=$1
-  skip=$2
-  count=$3
-  
-  checksum="$(dd if=$device skip=$skip count=$count bs=${mb_per_round}M 2>/dev/null | "$checksummer" - | awk '{print $1}')"
-  RET=$?
-  return $RET
+";
+  if (@ARGV > -1 ) {
+	print "\nError: " . shift . "\n";
+  }
+    exit;
 }
 
-copy_section() {
-  device_from=$1
-  device_to=$2
-  skip=$3
-  count=$4
-  
-  dd if=$device_from of=$device_to skip=$skip seek=$skip count=$count bs=${mb_per_round}M 2>/dev/null
+sub errout {
+	if (@ARGV > -1) {
+		print shift . "\n";
+	}
+	print "Program exited due to error.\n";
+	exit 1;
 }
 
-get_saved_sum() {
-  if ! [ -e "$saved_checksums" ] || ! [ -r "$saved_checksums" ] ; then
-    return 1
-  fi
-  section=$1
-  checksum_check="$(grep "^$section " "$saved_checksums" | awk '{print $2}')"
-  if [ -z "$checksum_check" ] ; then
-    return 1
-  fi
-  checksum=$checksum_check
-  return 0
+# get options
+my ($original, $backup);
+my $help = '';
+my $verbose = '';
+my $block_size=4096;
+my $checkonly='';
+my $verify='';
+my $start_place=1;
+my ($checksums_file, $checkpoint_file) = '';
+Getopt::Long::Configure ('bundling');
+if ( @ARGV > 0 ) {
+  GetOptions (
+   's|sums=s' => \$checksums_file, 
+   'b|block=i' => \$block_size,
+   'start=s' => \$start_place,
+   'savecp=s' => \$checkpoint_file,
+   'checkonly' => \$checkonly,
+   'verify' => \$verify,
+   'v|verbose!' => \$verbose,
+   'quiet'   => sub { $verbose = 0 },
+   'h|help|?' => \$help
+  );
+}
+else {
+	show_help("No options given. This program requires options.");
+}
+show_help() if ( $help );
+
+# get original and backup paths
+if ( $checkonly ) {
+	show_help if ( @ARGV == 0 );
+	$backup=shift;
+	# sanity checks
+	if ( not $checksums_file ) {
+		show_help("You must specify a checksums file");
+	}
+}
+else {
+	if ( $#ARGV != 1 ) {
+		show_help("You must specify an original and backup location");
+	}
+	$original=shift;
+	$backup=shift;
+	# sanity checks
+	if ( not $checksums_file ) {
+		show_help("You must specify a checksums file");
+	}
+	# do they exist?
+	if ( not -e $original ) {
+		errout("Cannot find $original") ;
+	}
+	if ( not -e $backup ){
+		errout("Cannot find $backup");
+	}
+		
+	
+
+	
+}	
+	
+	print $original . ' ' . $backup . "\n";
+	foreach (@ARGV) {
+		print $_ . "\n";
+	}
+
+#exit;
+
+# prompt (are you sure?)
+# override with -y
+
+# check and save every 100000 blocks (400M)
+my $save_every=100000;
+my $cache_count=0;
+
+if ( $checkpoint_file ) {
+	open(chk,'>',$checkpoint_file) || die "failed to open checkpoint file $checkpoint_file: $!";
+	chk->autoflush(1);
+	print chk "Start\n";
 }
 
-save_sum() {
-  if ! [ -e "$saved_checksums" ] || ! [ -r "$saved_checksums" ] ; then
-    return
-  fi
-  sum=$1
-  section=$2
-  # overwite checksum if needed
-  SUM_TMP_FILE=$(mktemp /dev/shm/checksum.XXXXXXXXXXXXXXXXX)
-  grep -v "^$section " "$saved_checksums" | grep -v "^SECTION SIZE " > "$SUM_TMP_FILE"
-  echo "$section $sum" >> "$SUM_TMP_FILE"
-  
-  echo "SECTION SIZE $mb_per_round" > "$saved_checksums"
-  cat "$SUM_TMP_FILE" | sort -n >> "$saved_checksums"
-  rm -f "$SUM_TMP_FILE"
+open(orig,$original) or die "Failed to open original: $original: $!";
+binmode(orig);
+
+open(back,'+<',$backup) or die "Failed to open backup: $backup: $!";
+binmode(back);
+
+my %backup_block_hashes ;
+my $db = tie %backup_block_hashes, 'BerkeleyDB::Btree',
+            -Filename   => $checksums_file,
+            -Flags      => DB_CREATE
+            or die "Cannot open checksums file $checksums_file: $! $BerkeleyDB::Error\n" ;
+
+# Add a key/value pair to the file
+
+#$backup_block_hashes{1} = 456345;
+
+# check/save block size
+if (exists $backup_block_hashes{0}) {
+	if ( $backup_block_hashes{0} != $block_size ) {
+		errout("The saved block size ". $backup_block_hashes{0} . 
+		" and your desired block size $block_size do not match\n".
+		"Cannot continue with the current settings\n");
+	}
+}
+else {
+	$backup_block_hashes{0} = $block_size;
 }
 
-# not needed with error check
-# amount=$(fdisk -l $original 2>/dev/null | grep "^Disk $original" | awk '{print $3}')
+sub do_cleanup {
+	print "Syncing and closing\n";
+	$db->db_sync();
+	fsync(\*back) or die "fsync: $!";
+	system("sync");
+	close(back);
+	exit;
+}	
 
-# check that devices do exist and are devices and can be dd'd
-error() {
-  echo $1
-  echo "For a list of options, try -h"
-  exit 1
+# trap signals
+$SIG{INT}  = \&do_cleanup;
+$SIG{HUP}  = \&do_cleanup;
+$SIG{TERM} = \&do_cleanup;
+$SIG{ALRM} = \&do_cleanup;
+
+
+# start matching
+my $x=$start_place;
+my ($n, $data, $digest);
+my ( $backup_data, $backup_digest);
+my $added=0;
+my $changed=0;
+my $rewrote=0;
+my %cached_changed_blocks=();
+my $current_added=0;
+my $current_changed=0;
+my $current_rewrote=0;
+my $backup_seek_pos=0;
+my $speed_start_time=time;
+my $speed_start_time_current_pass=time;
+
+seek(orig,($x * $block_size) - $block_size,0);
+while (($n = read orig, $data, $block_size) != 0) { 
+	# print "$n bytes read\n";
+	# $buf .= $data;
+#	$digest = md5_base64($data);
+	$digest = crc32($data);
+#	print save $digest . "\n";
+	if ( not exists $backup_block_hashes{$x} or $backup_block_hashes{$x} != $digest ) { 
+		# this will also be the checkonly one
+#		if ( $backup_seek_pos != $x ) {
+			#print "seeked to $x\n";
+			seek(back,($x * $block_size) - $block_size,0);
+#			$backup_seek_pos=$x;
+#		}
+		read(back, $backup_data, $block_size);
+#		$backup_seek_pos++;
+		$backup_digest = crc32($backup_data);
+		if ( $backup_block_hashes{$x} != $digest ) {
+			# print "changed from $backup_block_hashes{$x} at $x: $digest - $backup_digest\n";
+			$changed++;
+			$current_changed++;
+		}
+		if ($digest != $backup_digest ) {
+			# write
+			# print "chksum and wrote $x\n";
+			$rewrote++;
+			$current_rewrote++;
+#			if ( $backup_seek_pos != $x ) {
+				#print "seeked to $x\n";
+				seek(back,($x * $block_size) - $block_size,0);
+#				$backup_seek_pos=$x;
+#			}
+			print back $data;
+#			$backup_seek_pos++;
+		}
+		else {
+			# print "only added chksum $x!\n";
+			$added++;
+			$current_added++;
+		}
+		# add to cached list to verify
+		$cached_changed_blocks{$x}=$digest;
+		$cache_count++;
+		# save database only every $save_every (and verify it)
+		if ( $cache_count >= $save_every ) {
+			foreach (sort keys %cached_changed_blocks) {
+				my $b=$_;
+#				if ( $backup_seek_pos != $b ) {
+					#print "seeked to $b\n";
+					seek(back,($b * $block_size) - $block_size,0);
+#					$backup_seek_pos=$b;
+#				}
+				read(back, $backup_data, $block_size);
+#				$backup_seek_pos++;
+				$backup_digest = crc32($backup_data);
+				if ( $backup_digest != $cached_changed_blocks{$b} ) {
+					print "Block $b failed to write properly. Exiting.\n";
+					exit 1;
+					# todo: try to rewite and fix
+				}
+				$backup_block_hashes{$b} = $cached_changed_blocks{$b};
+			}
+			# sync
+			#system("sync");
+			#print "sync\n";
+			$db->db_sync();
+			fsync(\*back) or die "fsync: $!";
+			#fsync(\*chk) or die "fsync: $!";
+			# done checking and saving
+			# reset counter
+			$cache_count=0;
+			%cached_changed_blocks=();
+			# print stats
+			print "Chkpnt block $x: " . (int($current_changed/$save_every*100)) .
+				"% changes, $current_rewrote/$rewrote (".
+				(int($current_rewrote/$save_every*100)) .
+				"%) rewrites, $current_added/$added (".
+				(int($current_added/$save_every*100)) .
+				"%) db only, ";
+			# write to checkpoint file (hot write)
+			if ( $checkpoint_file ) {
+				print chk "Checkpoint: $x blocks, $changed changes, $rewrote rewrites, $added database only\n";
+			}
+			$current_added=0;
+			$current_changed=0;
+			$current_rewrote=0;
+			# print disk speeds
+			print int(($save_every * $block_size / 1024 / 1024 ) / (time - $speed_start_time_current_pass + 1)) . " Mb/s (";
+			$speed_start_time_current_pass=time;
+			print int(($x * $block_size / 1024 /1024 ) / (time - $speed_start_time +1)) . " Mb/s avg)\n";
+		}
+	} elsif ( $x % $save_every == 0 ) {
+		# if it's checking all blocks, we dont need to show this
+		print "Chkpnt block $x, ";
+		if ( $checkpoint_file ) {
+			print chk "Checkpoint: $x blocks, $changed changes, $rewrote rewrites, $added database only\n";
+		}
+		print int(($x * $block_size / 1024 /1024 ) / (time - $speed_start_time +1)) . " Mb/s\n";
+		# sync
+		#system("sync");
+		#print "sync\n";
+		$db->db_sync();
+		fsync(\*back) or die "fsync: $!";
+		#fsync(\*chk) or die "fsync: $!";
+	}
+	$x++;
+#	exit;
 }
 
-check_device() {
-  if ! [ -e "$1" ] ; then
-    error "$1 does not exist"
-  elif ! [ -r "$1" ] ; then
-    error "Cannot read $1"
-  fi
-  dd if="$1" count=1 bs=1 >/dev/null 2>&1
-  if [ $? -ne 0 ] ; then
-    echo "Tried to dd $1, but it did not like it."
-    echo -n "Are you sure you want to continue? (N/y) "
-    read RESP
-    if [ "$RESP" != "y" ] ; then
-      exit
-    fi
-  fi
+# finish writing changed blocks
+print $cache_count . "\n";
+if ( $cache_count > 0 ) {
+	foreach (sort keys %cached_changed_blocks) {
+		my $b=$_;
+		seek(back,($b * $block_size) - $block_size,0);
+		read(back, $backup_data, $block_size);
+		$backup_digest = crc32($backup_data);
+		if ( $backup_digest != $cached_changed_blocks{$b} ) {
+			print "Block $b failed to write properly. Exiting.\n";
+			exit 1;
+			# todo: try to rewite and fix
+		}
+		$backup_block_hashes{$b} = $cached_changed_blocks{$b};
+	}
+	# sync
+	$db->db_sync();
+	fsync(\*back) or die "fsync: $!";
+}
+$x--;
+my $total_checked=$x-$start_place;
+print "All done\n";
+print "Total of $x blocks on device\n";
+print $changed . " changes (".int($changed/$total_checked*100)."%)\n";
+print $rewrote . " rewrites to backup drive (".int($rewrote/$total_checked*100)."%)\n";
+print $added . " database only updates (".int($added/$total_checked*100)."%)\n";
+print "Speed was " . int(($x * $block_size / 1024 /1024 ) / (time - $speed_start_time +1)) . " Mb/s\n";
+
+if ( $checkpoint_file ) {
+	print chk "Finished: $x blocks, $changed changes, $rewrote rewrites, $added times only checksum was added\n";
 }
 
-######################
-# checks
+close(orig);
+do_cleanup();
 
-if [ -z "$check_only" ] ; then
-  check_device "$original"
-fi
-
-check_device "$backup"
-
-
-# check if saved checksums file exists and is right section size
-if [ -z "$check_only" ] ; then
-
-if [ -n "$saved_checksums" ] ; then
- if ! [ -e "$saved_checksums" ] ; then
-  echo "Warning: Saved checksums file $saved_checksums does not exist. File created."
-  echo "This is expected for your first run, but not subsequent runs"
-  echo
-  touch "$saved_checksums" || error "Cannot create checksum file $saved_checksums"
-
- elif [ "$(head -n 1 "$saved_checksums" | awk '{print $3}')" != "$mb_per_round" ] ; then
-  echo "Your saved checksum file is not for this size of breakups."
-  echo -n "Proceeding will destroy the saved checksums. Do you want to continue? (N/y) "
-  read RESP
-  if [ "$RESP" != "y" ] ; then
-    exit
-  fi
-  echo -n > "$saved_checksums"
-  echo
- fi
-fi
-
-else
-
-  if ! [ -f "$saved_checksums" ] ; then
-    error "Could not find saved checksums at $saved_checksums"
-  
-  fi
-  
-  # get size
-  mb_per_round="$(head -n 1 "$saved_checksums" | awk '{print $3}')"
-  
-fi
-    
-
-### check only ###
-
-if [ -n "$check_only" ] ; then
-  echo "Checking $backup, $mb_per_round mb at a time, with notices every $notify_every_mb mb."
-  PART=0
-  AT_END=0
-  notify_every=$(expr $notify_every_mb \/ $mb_per_round)
-  notify_timeout=$notify_every
-  while [ $AT_END -eq 0 ] ; do
-  
-    # get backup sum
-    get_saved_sum $PART
-    checksum_saved=$checksum
-    
-    # get actual sum
-    get_sum $backup $PART 1
-    if [ $? -ne 0 ] ; then
-       AT_END=$?
-       if [ $AT_END -ne 0 ] ; then
-         break
-       fi
-       # LOC1=$(expr $PART \* $mb_per_round)
-       # error "Failed to get checksum for section $LOC1 mb"
-    fi
-    checksum_backup=$checksum
-    
-    if [ "$checksum_saved" != "$checksum_backup" ] ; then
-      LOC1=$(expr $PART \* $mb_per_round)
-      LOC2=$(expr $LOC1 + $mb_per_round)
-      copy_section $original $backup $PART 1
-      echo "ERROR: Data is changed from $LOC1 mb to $LOC2 mb."
-      echo
-      echo "Saved: $checksum_saved"
-      echo "Got:   $checksum_backup"
-      echo
-      exit 1 #so scripts can decide to do a full check (no -s)
-    fi
-
-    # output
-    if [ $notify_timeout -le 0 ] ; then
-      LOC1=$(expr $PART \* $mb_per_round)
-      echo "Checked $LOC1 mb."
-      notify_timeout=$notify_every
-    else
-      notify_timeout=$(expr $notify_timeout - 1)
-    fi
-    
-    # next
-    PART=$(expr $PART + 1)
-
-  done
-  
-  echo "Check successful"
-  exit 0
-  
-fi
-
-    
-  
-
-
-### full copy ###
-
-# time to work
-echo "Checking and copying from $original to $backup,"
-echo "$mb_per_round mb at a time, with notices every $notify_every_mb mb."
-PART=0
-AT_END=0
-changed=0
-notify_every=$(expr $notify_every_mb \/ $mb_per_round)
-notify_timeout=$notify_every
-while [ $AT_END -eq 0 ] ; do
-  
-  # get original sum
-  get_sum $original $PART 1
-  AT_END=$?
-  if [ $AT_END -ne 0 ] ; then
-    break
-  fi
-  checksum_original=$checksum
-  
-  # get backup sum, preferrably from saved list
-  get_saved_sum $PART
-  if [ $? -ne 0 ] ; then
-    get_sum $backup $PART 1
-    if [ $? -ne 0 ] ; then
-       LOC1=$(expr $PART \* $mb_per_round)
-       error "Failed to get checksum for section $LOC1 mb"
-    fi
-    save_sum $checksum $PART
-  fi
-  checksum_backup=$checksum
-  
-  # we replay this to check that the data was copied correctly
-  correct=0
-  tries=3
-  while [ $correct -eq 0 ] && [ $tries -gt 0 ] ; do
-  
-  # compare it
-  if [ "$checksum_original" != "$checksum_backup" ] ; then
-    LOC1=$(expr $PART \* $mb_per_round)
-    LOC2=$(expr $LOC1 + $mb_per_round)
-    copy_section $original $backup $PART 1
-    echo "Copied changed data from $LOC1 mb to $LOC2 mb."
-    changed=$(expr $changed + 1)
-    # get checksum and save it
-    get_sum $backup $PART 1
-    checksum_backup=$checksum
-    save_sum $checksum $PART
-    #echo "Original: $checksum_original"
-    #echo "Backup:   $checksum_backup"
-    tries=$(expr $tries - 1)
-  else
-    # nothing to copy, so just move on
-    correct=1
-  fi
-  
-  done # replay
-  if [ $correct -eq 0 ] ; then
-    error "Failed to copy above section"
-  fi
-  
-  # output
-  if [ $notify_timeout -le 0 ] ; then
-    LOC1=$(expr $PART \* $mb_per_round)
-    echo "Checked $LOC1 mb."
-    notify_timeout=$notify_every
-  else
-    notify_timeout=$(expr $notify_timeout - 1)
-  fi
-
-#  # test - exit after X mb of data
-#  TOTAL=$(expr $PART \* $mb_per_round)
-#  if [ $TOTAL -ge 1000 ] ; then
-#    echo "Finished $TOTAL mb"
-#    exit
-#  fi
-
-  # next
-  PART=$(expr $PART + 1)
-  
-done
-
-percent=$( expr $changed \* 100 \/ $PART )
-
-echo "Finished. Changed $changed sections out of $PART, or about $percent percent."
